apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-po4r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-po4r
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-po4r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-po4r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-po4r
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-elrm-tenant/rhtap-demo-app/hacbs-test-project-po4r@sha256:96d9af4770738fbc11d2af81ffd1cdd6d7446f17d88034f529216e49e83fcdd7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
