apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-po4r
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-elrm-tenant/rhtap-demo-app/hacbs-test-project-po4r@sha256:96d9af4770738fbc11d2af81ffd1cdd6d7446f17d88034f529216e49e83fcdd7
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
